### ISSUE TITLE
pulling a request

### ISSUE THREAD

**Issue by patatetom** [micro-editor/plugin-channel#27]
hello, I followed the instructions given at the end of the page [plugins.md](https://github.com/zyedidia/micro/blob/master/runtime/help/plugins.md) but I'm unable to go to the step **Pull Request**.

https://github.com/patatetom/micro-sort-lines

regards.

**Comment by sum01** [comment]
See https://github.com/zyedidia/micro/issues/1072#issuecomment-373928388
